name: prestamo_mc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  #firebase
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  firebase_auth: ^4.1.2

  #get
  get: 4.6.5
  get_storage: ^2.0.3
  getwidget: ^3.0.1

  #others
  responsive_sizer: ^3.1.0  
  flutter_login: ^4.0.0
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  

  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  numeric_keyboard: ^1.1.0
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.3.50
  date_utils: ^0.2.0
  get_cli: ^0.2.30
  pdf: ^3.8.4
  printing: ^5.9.3
  path_provider: ^2.0.11
  infinite_listview: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  change_app_package_name: ^1.1.0


 

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
